"use client";

import { useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/input";
import { Dices, Check, CheckCircle2, ChevronRight, FileCode2, Copy } from "lucide-react";

interface BingoCommon {
  bingo_type: string;
  max_bingo_number: string;
  hidden_icon: string;
  reward_send_id: string;
  reward_state: string;
  reward_period: string;
  reward_ment: string;
}

interface BingoReward {
  reward_name: string;
  reward_icon: string;
  reward_hidden: string;
  reward_type: string;
  reward_value1: string;
  reward_value2: string;
  reward_percent: string;
  reward_manual: string;
}

const DEFAULT_REWARD: BingoReward = {
  reward_name: "STR(1)",
  reward_icon: "UIIconPack117#unique_extra3",
  reward_hidden: "0",
  reward_type: "5",
  reward_value1: "1000",
  reward_value2: "0",
  reward_percent: "100",
  reward_manual: "1"
};

export default function BingoGeneratorPage() {
  const [common, setCommon] = useState<BingoCommon>({
    bingo_type: "0",
    max_bingo_number: "50",
    hidden_icon: "UIIconPack46#goods_bingo06_hideitem",
    reward_send_id: "DeveloperK",
    reward_state: "0",
    reward_period: "7",
    reward_ment: "1011"
  });

  const [boardRewards, setBoardRewards] = useState<BingoReward[]>(
    Array.from({ length: 97 }, () => ({ ...DEFAULT_REWARD }))
  );

  const [lineRewards, setLineRewards] = useState<BingoReward[]>(
    Array.from({ length: 12 }, () => ({ ...DEFAULT_REWARD, reward_type: "3", reward_value2: "1", reward_manual: "21" }))
  );

  const [activeTab, setActiveTab] = useState("board");
  const [activeBoardIdx, setActiveBoardIdx] = useState(0);
  const [activeLineIdx, setActiveLineIdx] = useState(0);

  const [generatedOutput, setGeneratedOutput] = useState("");
  const [copied, setCopied] = useState(false);

  const updateCommon = (key: keyof BingoCommon, val: string) => {
    setCommon(prev => ({ ...prev, [key]: val }));
  };

  const updateBoard = (idx: number, key: keyof BingoReward, val: string) => {
    const newArr = [...boardRewards];
    newArr[idx] = { ...newArr[idx], [key]: val };
    setBoardRewards(newArr);
  };

  const updateLine = (idx: number, key: keyof BingoReward, val: string) => {
    const newArr = [...lineRewards];
    newArr[idx] = { ...newArr[idx], [key]: val };
    setLineRewards(newArr);
  };

  const handleGenerate = () => {
    let output = `;---------------------------------------------------------------
; Generated by Bingo Generator
;---------------------------------------------------------------
[common]
bingo_type\t=\t${common.bingo_type}
max_bingo_number\t=\t${common.max_bingo_number}
hidden_icon\t=\t${common.hidden_icon}

reward_send_id\t=\t${common.reward_send_id}
reward_state\t=\t${common.reward_state}
reward_period\t=\t${common.reward_period}
reward_ment\t=\t${common.reward_ment}

`;
    // Board Rewards
    boardRewards.forEach((r, idx) => {
      output += `[reward${idx + 1}]\t\t
reward_name\t\t=\t${r.reward_name}
reward_icon\t\t=\t${r.reward_icon}
reward_hidden\t=\t${r.reward_hidden}
reward_type\t\t=\t${r.reward_type}
reward_value1\t=\t${r.reward_value1}
reward_value2\t=\t${r.reward_value2}
reward_percent\t=\t${r.reward_percent}
reward_manual\t=\t${r.reward_manual}
\t\t
`;
    });

    // Line Rewards
    lineRewards.forEach((r, idx) => {
      output += `[allbingo_${idx + 1}]\t\t
reward_name\t\t=\t${r.reward_name}
reward_icon\t\t=\t${r.reward_icon}
reward_hidden\t=\t${r.reward_hidden}
reward_type\t\t=\t${r.reward_type}
reward_value1\t=\t${r.reward_value1}
reward_value2\t=\t${r.reward_value2}
reward_percent\t=\t${r.reward_percent}
reward_manual\t=\t${r.reward_manual}
\t\t
`;
    });

    setGeneratedOutput(output);
    setCopied(false);
  };

  const renderRewardForm = (reward: BingoReward, updater: (key: keyof BingoReward, val: string) => void) => (
    <div className="grid grid-cols-2 xl:grid-cols-3 gap-6">
      {Object.entries(reward).map(([key, val]) => (
        <div key={key} className="space-y-1.5">
          <label className="text-[10px] font-bold text-muted-foreground uppercase">{key}</label>
          <Input 
            value={val} 
            onChange={(e) => updater(key as keyof BingoReward, e.target.value)} 
            className="font-mono text-xs bg-background/50 border-border/50"
          />
        </div>
      ))}
    </div>
  );

  return (
    <div className="flex flex-col flex-1 p-8 h-full bg-background overflow-hidden">
      
      {/* Header */}
      <div className="mb-6 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-1.5 h-8 bg-purple-500 rounded-full"></div>
          <div>
            <h1 className="text-3xl font-bold tracking-tight mb-1">Bingo Generator</h1>
            <p className="text-muted-foreground text-sm font-medium">
              Easily generate <span className="font-mono text-purple-500/80">sp2_bingo.ini</span> definitions visually.
            </p>
          </div>
        </div>
        <Button 
          onClick={handleGenerate} 
          className="bg-purple-600 hover:bg-purple-700 text-white shadow-sm font-bold gap-2"
        >
          <FileCode2 className="w-4 h-4" />
          Generate INI
        </Button>
      </div>

      <div className="grid lg:grid-cols-3 gap-6 flex-1 min-h-0">
        
        <div className="lg:col-span-2 flex gap-6 h-full min-h-0">
          {/* LEFT PANEL */}
          <Card className="w-72 flex flex-col min-h-0 border-border/50 bg-card/50 backdrop-blur-sm shrink-0">
            <div className="flex flex-col h-full">
              <div className="p-3 border-b border-border/50 shrink-0">
                <div className="w-full grid grid-cols-3 h-9 bg-background/50 border border-border/50 rounded-md p-1 gap-1">
                  <button 
                    onClick={() => setActiveTab("common")}
                    className={`text-[10px] uppercase font-bold tracking-wider rounded-sm transition-all ${activeTab === 'common' ? 'bg-purple-500/10 text-purple-500 shadow-sm' : 'text-muted-foreground hover:bg-muted/50'}`}
                  >Global</button>
                  <button 
                    onClick={() => setActiveTab("board")}
                    className={`text-[10px] uppercase font-bold tracking-wider rounded-sm transition-all ${activeTab === 'board' ? 'bg-purple-500/10 text-purple-500 shadow-sm' : 'text-muted-foreground hover:bg-muted/50'}`}
                  >Board</button>
                  <button 
                    onClick={() => setActiveTab("line")}
                    className={`text-[10px] uppercase font-bold tracking-wider rounded-sm transition-all ${activeTab === 'line' ? 'bg-purple-500/10 text-purple-500 shadow-sm' : 'text-muted-foreground hover:bg-muted/50'}`}
                  >Line</button>
                </div>
              </div>
              
              <div className="flex-1 overflow-y-auto p-2">
                {activeTab === "common" && (
                  <div className="p-4 text-center text-sm text-muted-foreground/70 flex flex-col items-center justify-center h-full">
                    <Dices className="w-12 h-12 mb-4 opacity-20" />
                    Select Global Settings to edit common bingo configurations.
                  </div>
                )}

                {activeTab === "board" && (
                  <div className="space-y-1">
                    {boardRewards.map((_, idx) => (
                      <button
                        key={`board-${idx}`}
                        onClick={() => setActiveBoardIdx(idx)}
                        className={`w-full text-left px-3 py-2.5 rounded-md transition-all flex items-center justify-between group ${
                          activeBoardIdx === idx 
                          ? "bg-purple-500/10 border border-purple-500/20 text-purple-500" 
                          : "text-muted-foreground hover:bg-muted/50 border border-transparent"
                        }`}
                      >
                        <span className="text-xs font-bold uppercase tracking-wider">Reward {idx + 1}</span>
                        {activeBoardIdx === idx && <ChevronRight className="w-4 h-4 opacity-70" />}
                      </button>
                    ))}
                  </div>
                )}

                {activeTab === "line" && (
                  <div className="space-y-1">
                    {lineRewards.map((_, idx) => (
                      <button
                        key={`line-${idx}`}
                        onClick={() => setActiveLineIdx(idx)}
                        className={`w-full text-left px-3 py-2.5 rounded-md transition-all flex items-center justify-between group ${
                          activeLineIdx === idx 
                          ? "bg-purple-500/10 border border-purple-500/20 text-purple-500" 
                          : "text-muted-foreground hover:bg-muted/50 border border-transparent"
                        }`}
                      >
                        <span className="text-xs font-bold uppercase tracking-wider">All Bingo {idx + 1}</span>
                        {activeLineIdx === idx && <ChevronRight className="w-4 h-4 opacity-70" />}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </Card>

          {/* RIGHT PANEL - Editor */}
          <Card className="flex-1 flex flex-col min-h-0 border-border/50 bg-card/50 backdrop-blur-sm shadow-sm relative overflow-hidden">
            
            <CardHeader className="p-6 border-b border-border/50 shrink-0 bg-background/50">
              <CardTitle className="text-xl font-bold tracking-tight text-purple-500 flex items-center gap-3">
                {activeTab === "common" && "Global Bingo Settings"}
                {activeTab === "board" && `Board Reward [reward${activeBoardIdx + 1}]`}
                {activeTab === "line" && `Line Reward [allbingo_${activeLineIdx + 1}]`}
              </CardTitle>
              <CardDescription className="text-xs font-semibold mt-1">
                Edit the properties directly. Changes are automatically queued for generation.
              </CardDescription>
            </CardHeader>

            <div className="flex-1 overflow-y-auto p-6 space-y-8">
              
              {activeTab === "common" && (
                <div className="grid grid-cols-2 xl:grid-cols-3 gap-6">
                  {Object.entries(common).map(([key, val]) => (
                    <div key={key} className="space-y-1.5">
                      <label className="text-[10px] font-bold text-muted-foreground uppercase">{key}</label>
                      <Input 
                        value={val} 
                        onChange={(e) => updateCommon(key as keyof BingoCommon, e.target.value)} 
                        className="font-mono text-xs bg-background/50 border-border/50"
                      />
                    </div>
                  ))}
                </div>
              )}

              {activeTab === "board" && renderRewardForm(boardRewards[activeBoardIdx], (k, v) => updateBoard(activeBoardIdx, k, v))}
              {activeTab === "line" && renderRewardForm(lineRewards[activeLineIdx], (k, v) => updateLine(activeLineIdx, k, v))}
            </div>
          </Card>
        </div>

        {/* OUTPUT COLUMN */}
        <div className="flex flex-col gap-6 h-full min-h-0">
          <Card className="border-border/50 bg-card/50 backdrop-blur-sm shadow-sm flex-1 flex flex-col min-h-0">
            <CardHeader className="pb-4 border-b border-border/50 flex flex-row items-center justify-between shrink-0">
              <CardTitle className="text-lg font-bold flex items-center gap-2">
                Output INI
              </CardTitle>
              <Button 
                variant="outline" 
                size="sm" 
                className="gap-2 font-bold shadow-sm h-8"
                onClick={() => {
                  if(!generatedOutput) return;
                  navigator.clipboard.writeText(generatedOutput);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                }}
              >
                {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied" : "Copy"}
              </Button>
            </CardHeader>
            
            <div className="flex-1 p-0 relative group overflow-hidden">
              {!generatedOutput && (
                <div className="absolute inset-0 flex items-center justify-center flex-col text-muted-foreground/50 z-10">
                  <FileCode2 className="w-8 h-8 mb-2 opacity-50" />
                  <p className="text-sm font-medium">Click Generate INI first</p>
                </div>
              )}
              <textarea 
                className="w-full h-full bg-transparent border-0 resize-none font-mono text-[11px] leading-relaxed p-6 text-foreground/80 focus:outline-none shadow-none"
                readOnly
                placeholder="; Generated output will appear here..."
                value={generatedOutput}
                spellCheck={false}
              />
            </div>
          </Card>
        </div>

      </div>
    </div>
  );
}
