"use client";

import { useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/input";
import { Trophy, CheckCircle2, ChevronRight, FileCode2, Copy } from "lucide-react";

interface TourneyCommon {
  present_ment: string;
  present_period: string;
  max: string;
}

interface TourneyReward {
  title: string;
  etc_item_type: string;
  reward_item_pirce: string;
}

const DEFAULT_REWARD: TourneyReward = {
  title: "STR(1)",
  etc_item_type: "1001713",
  reward_item_pirce: "3"
};

export default function TournamentGeneratorPage() {
  const [common, setCommon] = useState<TourneyCommon>({
    present_ment: "1006",
    present_period: "14",
    max: "32"
  });

  const [rewards, setRewards] = useState<TourneyReward[]>(
    Array.from({ length: 32 }, () => ({ ...DEFAULT_REWARD }))
  );

  const [activeTab, setActiveTab] = useState("common");
  const [activeRewardIdx, setActiveRewardIdx] = useState(0);

  const [generatedOutput, setGeneratedOutput] = useState("");
  const [copied, setCopied] = useState(false);

  const updateCommon = (key: keyof TourneyCommon, val: string) => {
    setCommon(prev => ({ ...prev, [key]: val }));
    // If they change max, we could dynamically resize the array, but for safety in this editor
    // we'll keep the array flexible or just let it be. Let's resize if needed.
    if (key === "max") {
      const maxInt = parseInt(val) || 0;
      if (maxInt > 0 && maxInt <= 1000) {
        setRewards(prev => {
          if (maxInt > prev.length) {
            return [...prev, ...Array.from({ length: maxInt - prev.length }, () => ({ ...DEFAULT_REWARD }))];
          } else if (maxInt < prev.length) {
            return prev.slice(0, maxInt);
          }
          return prev;
        });
      }
    }
  };

  const updateReward = (idx: number, key: keyof TourneyReward, val: string) => {
    const newArr = [...rewards];
    newArr[idx] = { ...newArr[idx], [key]: val };
    setRewards(newArr);
  };

  const handleGenerate = () => {
    let output = `;---------------------------------------------------------------
; Generated by Tournament Reward Generator
;---------------------------------------------------------------
[common]
present_ment\t=\t${common.present_ment}
present_period\t=\t${common.present_period}

max\t=\t${common.max}
`;

    rewards.forEach((r, idx) => {
      output += `
[rewarditem${idx + 1}]
title\t=\t${r.title}
etc_item_type\t=\t${r.etc_item_type}
reward_item_pirce\t=\t${r.reward_item_pirce}
`;
    });

    setGeneratedOutput(output);
    setCopied(false);
  };

  return (
    <div className="flex flex-col flex-1 p-8 h-full bg-background overflow-hidden">
      
      {/* Header */}
      <div className="mb-6 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-1.5 h-8 bg-cyan-500 rounded-full"></div>
          <div>
            <h1 className="text-3xl font-bold tracking-tight mb-1">Tournament Gen</h1>
            <p className="text-muted-foreground text-sm font-medium">
              Generator visual untuk <span className="font-mono text-cyan-500/80">sp2_custom_tournament_reward.ini</span>.
            </p>
          </div>
        </div>
        <Button 
          onClick={handleGenerate} 
          className="bg-cyan-600 hover:bg-cyan-700 text-white shadow-sm font-bold gap-2"
        >
          <FileCode2 className="w-4 h-4" />
          Generate INI
        </Button>
      </div>

      <div className="grid lg:grid-cols-3 gap-6 flex-1 min-h-0">
        
        <div className="lg:col-span-2 flex gap-6 h-full min-h-0">
          {/* LEFT PANEL */}
          <Card className="w-72 flex flex-col min-h-0 border-border/50 bg-card/50 backdrop-blur-sm shrink-0">
            <div className="flex flex-col h-full">
              <div className="p-3 border-b border-border/50 shrink-0">
                <div className="w-full grid grid-cols-2 h-9 bg-background/50 border border-border/50 rounded-md p-1 gap-1">
                  <button 
                    onClick={() => setActiveTab("common")}
                    className={`text-[10px] uppercase font-bold tracking-wider rounded-sm transition-all ${activeTab === 'common' ? 'bg-cyan-500/10 text-cyan-500 shadow-sm' : 'text-muted-foreground hover:bg-muted/50'}`}
                  >Global</button>
                  <button 
                    onClick={() => setActiveTab("rewards")}
                    className={`text-[10px] uppercase font-bold tracking-wider rounded-sm transition-all ${activeTab === 'rewards' ? 'bg-cyan-500/10 text-cyan-500 shadow-sm' : 'text-muted-foreground hover:bg-muted/50'}`}
                  >Rewards</button>
                </div>
              </div>
              
              <div className="flex-1 overflow-y-auto p-2">
                {activeTab === "common" && (
                  <div className="p-4 text-center text-sm text-muted-foreground/70 flex flex-col items-center justify-center h-full">
                    <Trophy className="w-12 h-12 mb-4 opacity-20" />
                    Atur parameter global turnamen di panel Editor sebelah kanan.
                  </div>
                )}

                {activeTab === "rewards" && (
                  <div className="space-y-1">
                    {rewards.map((_, idx) => (
                      <button
                        key={`reward-${idx}`}
                        onClick={() => setActiveRewardIdx(idx)}
                        className={`w-full text-left px-3 py-2.5 rounded-md transition-all flex items-center justify-between group ${
                          activeRewardIdx === idx 
                          ? "bg-cyan-500/10 border border-cyan-500/20 text-cyan-500" 
                          : "text-muted-foreground hover:bg-muted/50 border border-transparent"
                        }`}
                      >
                        <span className="text-xs font-bold uppercase tracking-wider">Reward {idx + 1}</span>
                        {activeRewardIdx === idx && <ChevronRight className="w-4 h-4 opacity-70" />}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </Card>

          {/* RIGHT PANEL - Editor */}
          <Card className="flex-1 flex flex-col min-h-0 border-border/50 bg-card/50 backdrop-blur-sm shadow-sm relative overflow-hidden">
            
            <CardHeader className="p-6 border-b border-border/50 shrink-0 bg-background/50">
              <CardTitle className="text-xl font-bold tracking-tight text-cyan-500 flex items-center gap-3">
                {activeTab === "common" && "Global Tournament Settings"}
                {activeTab === "rewards" && `Reward Item [rewarditem${activeRewardIdx + 1}]`}
              </CardTitle>
              <CardDescription className="text-xs font-semibold mt-1">
                Ubah parameter di bawah ini secara real-time.
              </CardDescription>
            </CardHeader>

            <div className="flex-1 overflow-y-auto p-6 space-y-8">
              
              {activeTab === "common" && (
                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-muted-foreground uppercase">Present Ment</label>
                    <Input 
                      value={common.present_ment} 
                      onChange={(e) => updateCommon("present_ment", e.target.value)} 
                      className="font-mono text-xs bg-background/50 border-border/50"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-bold text-muted-foreground uppercase">Present Period</label>
                    <Input 
                      value={common.present_period} 
                      onChange={(e) => updateCommon("present_period", e.target.value)} 
                      className="font-mono text-xs bg-background/50 border-border/50"
                    />
                  </div>
                  <div className="space-y-1.5 col-span-2">
                    <label className="text-[10px] font-bold text-muted-foreground uppercase">Max Rewards</label>
                    <Input 
                      value={common.max} 
                      onChange={(e) => updateCommon("max", e.target.value)} 
                      className="font-mono text-xs bg-background/50 border-border/50"
                      type="number"
                      min="1"
                    />
                    <p className="text-[10px] text-muted-foreground mt-1">Mengubah nilai ini akan menambah/mengurangi slot hadiah di tab Rewards secara otomatis.</p>
                  </div>
                </div>
              )}

              {activeTab === "rewards" && (
                <div className="grid grid-cols-2 gap-6">
                  {Object.entries(rewards[activeRewardIdx]).map(([key, val]) => (
                    <div key={key} className={`space-y-1.5 ${key === 'title' ? 'col-span-2' : ''}`}>
                      <label className="text-[10px] font-bold text-muted-foreground uppercase">{key}</label>
                      <Input 
                        value={val} 
                        onChange={(e) => updateReward(activeRewardIdx, key as keyof TourneyReward, e.target.value)} 
                        className="font-mono text-xs bg-background/50 border-border/50"
                      />
                      {key === "reward_item_pirce" && (
                        <p className="text-[10px] text-yellow-500/80 font-semibold">*Pirce (Typo asli dari sistem game, biarkan seperti ini)</p>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </Card>
        </div>

        {/* OUTPUT COLUMN */}
        <div className="flex flex-col gap-6 h-full min-h-0">
          <Card className="border-border/50 bg-card/50 backdrop-blur-sm shadow-sm flex-1 flex flex-col min-h-0">
            <CardHeader className="pb-4 border-b border-border/50 flex flex-row items-center justify-between shrink-0">
              <CardTitle className="text-lg font-bold flex items-center gap-2">
                Output INI
              </CardTitle>
              <Button 
                variant="outline" 
                size="sm" 
                className="gap-2 font-bold shadow-sm h-8"
                onClick={() => {
                  if(!generatedOutput) return;
                  navigator.clipboard.writeText(generatedOutput);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                }}
              >
                {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied" : "Copy"}
              </Button>
            </CardHeader>
            
            <div className="flex-1 p-0 relative group overflow-hidden">
              {!generatedOutput && (
                <div className="absolute inset-0 flex items-center justify-center flex-col text-muted-foreground/50 z-10">
                  <FileCode2 className="w-8 h-8 mb-2 opacity-50" />
                  <p className="text-sm font-medium">Click Generate INI first</p>
                </div>
              )}
              <textarea 
                className="w-full h-full bg-transparent border-0 resize-none font-mono text-[11px] leading-relaxed p-6 text-foreground/80 focus:outline-none shadow-none"
                readOnly
                placeholder="; Generated output will appear here..."
                value={generatedOutput}
                spellCheck={false}
              />
            </div>
          </Card>
        </div>

      </div>
    </div>
  );
}
